### ISSUE TITLE
Links to Linux-only libraries causing test failures on OS X.

### ISSUE THREAD

**Issue by robshakir** [openconfig/lemming#225]
@wenovus migrated a number of other projects to use lemming as the fake that they test against, great. Unfortunately, today since the dataplane links against Linux-only libraries, this means that these tests are now broken on OS X targets.

e.g., [`openconfig/gribigo`](https://github.com/openconfig/gribigo) tests fail like this:

```
[4:16] github.com/openconfig/gribigo   reconnreset ✔                                                                                                                                                                                  10m ⚑  
▶ go test -race $(go list ./... | egrep -v "(compliance|cmd|device)")
package github.com/openconfig/gribigo/cmd/rtr
	imports github.com/openconfig/lemming
	imports github.com/openconfig/lemming/dataplane
	imports github.com/openconfig/lemming/dataplane/forwarding
	imports github.com/openconfig/lemming/dataplane/forwarding/fwdport/ports
	imports github.com/google/gopacket/afpacket: build constraints exclude all Go files in /Users/rjs/go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket
go: downloading github.com/openconfig/testt v0.0.0-20220311054427-efbb1a32ec07
go: downloading github.com/pmezard/go-difflib v1.0.0
# github.com/openconfig/gribigo/fluent
package github.com/openconfig/gribigo/fluent (test)
	imports github.com/openconfig/lemming
	imports github.com/openconfig/lemming/dataplane
	imports github.com/openconfig/lemming/dataplane/forwarding
	imports github.com/openconfig/lemming/dataplane/forwarding/fwdport/ports
	imports github.com/google/gopacket/afpacket: build constraints exclude all Go files in /Users/rjs/go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket
```

Given that these tests do not use the dataplane, this seems undesirable - and makes lemming unsuitable for being a fake for development for these projects.

Please investigate using build tags or some other solution to fix this :-)

**Comment by robshakir** [comment]
There's a major regression in build time as well for gribigo based on having moved to lemming and the size of the build.

It seems like there should be some modularity such that one can simply spin up the control plane for e.g., gribigo tests, where the entire unit seems overkill.

**Comment by DanG100** [comment]
This is fixed in https://github.com/openconfig/lemming/pull/229

**Comment by robshakir** [comment]
Nice work! Thanks @DanG100 !
